-- MySQL dump 10.13  Distrib 5.5.37, for debian-linux-gnu (i686)
--
-- Host: localhost    Database: LMS
-- ------------------------------------------------------
-- Server version	5.5.37-0ubuntu0.12.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Current Database: `LMS`
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `LMS` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `LMS`;

--
-- Table structure for table `bands_details`
--

DROP TABLE IF EXISTS `bands_details`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bands_details` (
  `band_id` int(11) NOT NULL AUTO_INCREMENT,
  `band_name` varchar(64) NOT NULL,
  `band_image` text NOT NULL COMMENT 'Path to image stored on server',
  `band_permalink` varchar(32) NOT NULL COMMENT 'Generated by script on registration',
  `band_genre_id` int(11) NOT NULL COMMENT 'Linked to bands_genres',
  `band_subgenre1` varchar(64) NOT NULL COMMENT 'Free Text on registration',
  `band_subgenre2` varchar(64) NOT NULL COMMENT 'Free Text on registration',
  `band_info` text NOT NULL COMMENT 'Band Bio',
  `contact_name` varchar(64) NOT NULL,
  `contact_phone` varchar(12) NOT NULL COMMENT 'in format 353861234567',
  `contact_email` varchar(100) NOT NULL,
  `registered_student_id` int(9) NOT NULL,
  `admin_approved` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`band_id`),
  UNIQUE KEY `band_permalink` (`band_permalink`),
  KEY `band_genre_id` (`band_genre_id`),
  CONSTRAINT `bands_details_ibfk_1` FOREIGN KEY (`band_genre_id`) REFERENCES `bands_genres` (`genre_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bands_genres`
--

DROP TABLE IF EXISTS `bands_genres`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bands_genres` (
  `genre_id` int(11) NOT NULL AUTO_INCREMENT,
  `genre_name` varchar(64) NOT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE KEY `genre_name` (`genre_name`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bands_links`
--

DROP TABLE IF EXISTS `bands_links`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bands_links` (
  `link_id` int(11) NOT NULL AUTO_INCREMENT,
  `band_id` int(11) NOT NULL,
  `link_url` varchar(512) NOT NULL,
  `link_title` varchar(64) NOT NULL,
  PRIMARY KEY (`link_id`),
  KEY `band_id` (`band_id`),
  CONSTRAINT `bands_links_ibfk_1` FOREIGN KEY (`band_id`) REFERENCES `bands_details` (`band_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bands_users`
--

DROP TABLE IF EXISTS `bands_users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bands_users` (
  `band_id` int(11) NOT NULL,
  `username` varchar(32) NOT NULL,
  `password` varchar(32) NOT NULL,
  `last_active` datetime NOT NULL,
  PRIMARY KEY (`band_id`),
  UNIQUE KEY `username` (`username`),
  CONSTRAINT `bands_users_ibfk_1` FOREIGN KEY (`band_id`) REFERENCES `bands_details` (`band_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `botb_bands`
--

DROP TABLE IF EXISTS `botb_bands`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `botb_bands` (
  `botb_band_id` int(11) NOT NULL AUTO_INCREMENT,
  `heat_id` int(11) NOT NULL,
  `entry_id` int(11) NOT NULL COMMENT 'Undecided as to whether bands will be linked to database, or info stored separately for BOTB. Depends on whether bands need to be in DB to enter BOTB',
  `prog_wildcard` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 if the band has moved on to Wildcard Round',
  `prog_final` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 if the band has moved on to the final',
  PRIMARY KEY (`botb_band_id`),
  KEY `heat_id` (`heat_id`),
  KEY `entry_id` (`entry_id`),
  CONSTRAINT `botb_bands_ibfk_1` FOREIGN KEY (`heat_id`) REFERENCES `botb_heats` (`heat_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `botb_heats`
--

DROP TABLE IF EXISTS `botb_heats`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `botb_heats` (
  `heat_id` int(11) NOT NULL AUTO_INCREMENT,
  `heat_date` datetime NOT NULL COMMENT 'year from this column can be used to restrict to current year on site (cos I''ll forget this otherwise)',
  `is_wildcard` tinyint(1) NOT NULL DEFAULT '0',
  `is_final` tinyint(1) NOT NULL DEFAULT '0',
  `num_bands` int(1) NOT NULL,
  PRIMARY KEY (`heat_id`),
  UNIQUE KEY `heat_date` (`heat_date`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cms_auth_levels`
--

DROP TABLE IF EXISTS `cms_auth_levels`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cms_auth_levels` (
  `auth_level` int(2) NOT NULL,
  `auth_level_label` varchar(32) NOT NULL,
  `auth_level_desc` varchar(256) NOT NULL,
  PRIMARY KEY (`auth_level`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cms_pages`
--

DROP TABLE IF EXISTS `cms_pages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cms_pages` (
  `page_id` int(11) NOT NULL AUTO_INCREMENT,
  `page_title` varchar(32) NOT NULL,
  `in_nav_bar` tinyint(1) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `page_content` longtext NOT NULL COMMENT 'content of the page stored as html',
  `nav_bar_pos` int(11) DEFAULT NULL COMMENT 'should be NULL when in_nav_bar = 0',
  PRIMARY KEY (`page_id`),
  UNIQUE KEY `nav_bar_pos` (`nav_bar_pos`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cms_users`
--

DROP TABLE IF EXISTS `cms_users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cms_users` (
  `user_id` int(5) NOT NULL AUTO_INCREMENT,
  `username` varchar(32) NOT NULL,
  `password` varchar(32) NOT NULL,
  `name` varchar(50) NOT NULL,
  `auth_level` int(2) NOT NULL COMMENT 'From authLevel table',
  `email` varchar(100) NOT NULL,
  `last_active` datetime NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `auth_level` (`auth_level`),
  CONSTRAINT `cms_users_ibfk_1` FOREIGN KEY (`auth_level`) REFERENCES `cms_auth_levels` (`auth_level`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `gallery_albums`
--

DROP TABLE IF EXISTS `gallery_albums`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gallery_albums` (
  `album_id` int(11) NOT NULL AUTO_INCREMENT,
  `album_title` varchar(255) NOT NULL,
  `album_desc` text NOT NULL,
  PRIMARY KEY (`album_id`),
  UNIQUE KEY `album_title` (`album_title`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `gallery_images`
--

DROP TABLE IF EXISTS `gallery_images`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gallery_images` (
  `image_id` int(11) NOT NULL AUTO_INCREMENT,
  `album_id` int(11) NOT NULL,
  `caption` varchar(255) NOT NULL,
  `subcaption` varchar(255) NOT NULL,
  `image_url` varchar(255) NOT NULL COMMENT 'absolute url of the image on the server',
  PRIMARY KEY (`image_id`),
  KEY `album_id` (`album_id`),
  CONSTRAINT `gallery_images_ibfk_1` FOREIGN KEY (`album_id`) REFERENCES `gallery_albums` (`album_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `newsletter`
--

DROP TABLE IF EXISTS `newsletter`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `newsletter` (
  `newsletter_id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `date` varchar(17) NOT NULL COMMENT 'should probably be changed to DATE type and formatted in program',
  `content` longtext NOT NULL COMMENT 'content of newsletter stored as html',
  PRIMARY KEY (`newsletter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tv_questions`
--

DROP TABLE IF EXISTS `tv_questions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tv_questions` (
  `question_id` int(11) NOT NULL AUTO_INCREMENT,
  `interview_id` int(11) NOT NULL COMMENT 'from tv_upcoming_interviews',
  `name` varchar(64) NOT NULL,
  `question` text NOT NULL,
  PRIMARY KEY (`question_id`),
  KEY `interview_id` (`interview_id`),
  CONSTRAINT `tv_questions_ibfk_1` FOREIGN KEY (`interview_id`) REFERENCES `tv_upcoming_interviews` (`interview_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tv_upcoming_interviews`
--

DROP TABLE IF EXISTS `tv_upcoming_interviews`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tv_upcoming_interviews` (
  `interview_id` int(11) NOT NULL AUTO_INCREMENT,
  `artist` varchar(64) NOT NULL,
  `close_time` datetime NOT NULL,
  `interview_date` date NOT NULL,
  PRIMARY KEY (`interview_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tv_videos`
--

DROP TABLE IF EXISTS `tv_videos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tv_videos` (
  `video_id` int(11) NOT NULL AUTO_INCREMENT,
  `youtube_link` varchar(512) NOT NULL,
  `image` varchar(256) NOT NULL,
  `video_title` varchar(64) NOT NULL,
  `video_permalink` varchar(32) NOT NULL,
  PRIMARY KEY (`video_id`),
  UNIQUE KEY `youtube_link` (`youtube_link`),
  UNIQUE KEY `video_permalink` (`video_permalink`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2014-07-03 12:18:17
